//! Pure PAC (`proxy.pac` / `wpad.dat`) body generation.

use rustcache_core::excl::Matcher;

use crate::config::schema::PacMode;

pub struct PacParams<'a> {
    pub proxy_host: &'a str,
    pub http_port: u16,
    /// MITM listener port — HTTPS must hit this port for per-request cache/log.
    pub https_port: u16,
    pub socks_port: u16,
    pub mode: PacMode,
    pub matchers: &'a [Matcher],
}

/// Bracket IPv6 literals for `host:port` interpolation in PAC returns.
pub fn pac_host(host: &str) -> String {
    if host.contains(':') && !host.starts_with('[') {
        format!("[{host}]")
    } else {
        host.to_string()
    }
}

/// Render `FindProxyForURL` for the given params.
///
/// JS matcher semantics mirror `rustcache_core::excl::matchers::Matcher`.
/// HTTPS is routed to the MITM port: the plain HTTP proxy only tunnels CONNECT.
pub fn generate_pac(p: &PacParams<'_>) -> String {
    let h = pac_host(p.proxy_host);
    let https_return = match p.mode {
        PacMode::Socks => format!("SOCKS5 {h}:{}; DIRECT", p.socks_port),
        _ => format!("PROXY {h}:{}; DIRECT", p.https_port),
    };
    let http_return = match p.mode {
        PacMode::Http => format!("PROXY {h}:{}; DIRECT", p.http_port),
        PacMode::Socks => format!("SOCKS5 {h}:{}; DIRECT", p.socks_port),
        PacMode::HttpSocks => format!(
            "PROXY {h}:{}; SOCKS5 {h}:{}; DIRECT",
            p.http_port, p.socks_port
        ),
    };

    let mut body = String::new();
    body.push_str("// Generated by RustCache — do not edit.\n");
    body.push_str("function FindProxyForURL(url, host) {\n");
    body.push_str("    if (isPlainHostName(host)) return \"DIRECT\";\n");

    for m in p.matchers {
        if let Some(line) = matcher_to_js(m) {
            body.push_str(&line);
        }
    }

    if https_return != http_return {
        body.push_str(&format!(
            "    if (url.substring(0, 6) === \"https:\") return \"{https_return}\";\n"
        ));
    }
    body.push_str(&format!("    return \"{http_return}\";\n"));
    body.push_str("}\n");
    body
}

/// One exclusion rule as a JS `return "DIRECT"` guard, or `None` for skippable rules (IPv6 CIDR).
fn matcher_to_js(m: &Matcher) -> Option<String> {
    match m {
        Matcher::Exact { value } => Some(format!(
            "    if (host === \"{v}\") return \"DIRECT\";\n",
            v = js_escape(value)
        )),
        Matcher::Wildcard { value } => Some(format!(
            "    if (shExpMatch(host, \"*.{v}\")) return \"DIRECT\";\n",
            v = js_escape(value)
        )),
        Matcher::Suffix { value } => Some(format!(
            "    if (host === \"{v}\" || dnsDomainIs(host, \".{v}\")) return \"DIRECT\";\n",
            v = js_escape(value)
        )),
        Matcher::Cidr { value, .. } => {
            let mask = cidr_to_netmask(value)?;
            let net = value.split('/').next().unwrap_or("");
            Some(format!(
                "    var _ip = dnsResolve(host);\n    if (_ip && isInNet(_ip, \"{net}\", \"{mask}\")) return \"DIRECT\";\n",
                net = js_escape(net),
                mask = js_escape(&mask)
            ))
        }
    }
}

/// `"10.0.0.0/8"` → `"255.0.0.0"`. IPv6 CIDR or malformed input → `None`.
pub fn cidr_to_netmask(cidr: &str) -> Option<String> {
    let (addr, prefix) = cidr.split_once('/')?;
    if addr.contains(':') {
        return None;
    }
    let prefix: u32 = prefix.parse().ok()?;
    if prefix > 32 {
        return None;
    }
    let mask: u32 = if prefix == 0 {
        0
    } else {
        u32::MAX << (32 - prefix)
    };
    Some(format!(
        "{}.{}.{}.{}",
        (mask >> 24) & 0xff,
        (mask >> 16) & 0xff,
        (mask >> 8) & 0xff,
        mask & 0xff
    ))
}

/// Minimal escaping for values embedded in double-quoted JS string literals.
fn js_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn params<'a>(mode: PacMode, matchers: &'a [Matcher]) -> PacParams<'a> {
        PacParams {
            proxy_host: "192.168.1.5",
            http_port: 3128,
            https_port: 3129,
            socks_port: 1080,
            mode,
            matchers,
        }
    }

    #[test]
    fn mode_strings() {
        let empty: Vec<Matcher> = vec![];
        let http = generate_pac(&params(PacMode::Http, &empty));
        assert!(http.contains("return \"PROXY 192.168.1.5:3128; DIRECT\";"));
        assert!(http.contains(
            "if (url.substring(0, 6) === \"https:\") return \"PROXY 192.168.1.5:3129; DIRECT\";"
        ));
        assert!(!http.contains("SOCKS5"));

        let socks = generate_pac(&params(PacMode::Socks, &empty));
        assert!(socks.contains("return \"SOCKS5 192.168.1.5:1080; DIRECT\";"));
        assert!(!socks.contains("PROXY "));

        let both = generate_pac(&params(PacMode::HttpSocks, &empty));
        assert!(
            both.contains("return \"PROXY 192.168.1.5:3128; SOCKS5 192.168.1.5:1080; DIRECT\";")
        );
        assert!(both.contains(
            "if (url.substring(0, 6) === \"https:\") return \"PROXY 192.168.1.5:3129; DIRECT\";"
        ));
    }

    #[test]
    fn https_uses_mitm_port() {
        let empty: Vec<Matcher> = vec![];
        let pac = generate_pac(&params(PacMode::HttpSocks, &empty));
        let https_line = pac
            .lines()
            .find(|l| l.contains("https:"))
            .expect("https branch");
        assert!(https_line.contains(":3129"));
        assert!(!https_line.contains(":3128"));
    }

    #[test]
    fn plain_host_is_direct() {
        let empty: Vec<Matcher> = vec![];
        let pac = generate_pac(&params(PacMode::Http, &empty));
        assert!(pac.contains("isPlainHostName(host)"));
        assert!(pac.starts_with("// Generated by RustCache"));
        assert!(pac.contains("function FindProxyForURL(url, host)"));
    }

    #[test]
    fn exact_matcher() {
        let ms = vec![Matcher::Exact {
            value: "bank.example".into(),
        }];
        let pac = generate_pac(&params(PacMode::Http, &ms));
        assert!(pac.contains("if (host === \"bank.example\") return \"DIRECT\";"));
    }

    #[test]
    fn wildcard_matcher_no_apex() {
        let ms = vec![Matcher::Wildcard {
            value: "local".into(),
        }];
        let pac = generate_pac(&params(PacMode::Http, &ms));
        assert!(pac.contains("if (shExpMatch(host, \"*.local\")) return \"DIRECT\";"));
        assert!(!pac.contains("host === \"local\""));
    }

    #[test]
    fn suffix_matcher_includes_apex() {
        let ms = vec![Matcher::Suffix {
            value: "example.com".into(),
        }];
        let pac = generate_pac(&params(PacMode::Http, &ms));
        assert!(pac.contains("if (host === \"example.com\" || dnsDomainIs(host, \".example.com\")) return \"DIRECT\";"));
    }

    #[test]
    fn cidr_matcher_uses_is_in_net() {
        let ms = Matcher::parse("10.0.0.0/8");
        let pac = generate_pac(&params(PacMode::Http, &ms));
        assert!(pac.contains("isInNet(_ip, \"10.0.0.0\", \"255.0.0.0\")"));
    }

    #[test]
    fn ipv6_cidr_skipped() {
        let ms = Matcher::parse("fd00::/8");
        let pac = generate_pac(&params(PacMode::Http, &ms));
        assert!(!pac.contains("isInNet"));
        assert!(pac.contains("return \"PROXY"));
    }

    #[test]
    fn cidr_to_netmask_cases() {
        assert_eq!(cidr_to_netmask("10.0.0.0/0").as_deref(), Some("0.0.0.0"));
        assert_eq!(cidr_to_netmask("10.0.0.0/8").as_deref(), Some("255.0.0.0"));
        assert_eq!(
            cidr_to_netmask("192.168.0.0/16").as_deref(),
            Some("255.255.0.0")
        );
        assert_eq!(
            cidr_to_netmask("192.168.1.0/24").as_deref(),
            Some("255.255.255.0")
        );
        assert_eq!(
            cidr_to_netmask("192.168.1.1/32").as_deref(),
            Some("255.255.255.255")
        );
        assert_eq!(cidr_to_netmask("fd00::/8"), None);
        assert_eq!(cidr_to_netmask("10.0.0.0/33"), None);
        assert_eq!(cidr_to_netmask("10.0.0.0"), None);
    }

    #[test]
    fn empty_exclusions_still_emits_function() {
        let empty: Vec<Matcher> = vec![];
        let pac = generate_pac(&params(PacMode::HttpSocks, &empty));
        assert!(pac.contains("function FindProxyForURL"));
        assert!(pac.contains("PROXY 192.168.1.5:3128"));
        assert!(pac.contains("PROXY 192.168.1.5:3129"));
    }

    #[test]
    fn pac_host_brackets_ipv6() {
        assert_eq!(pac_host("::1"), "[::1]");
        assert_eq!(pac_host("2001:db8::1"), "[2001:db8::1]");
        assert_eq!(pac_host("192.168.1.5"), "192.168.1.5");
        assert_eq!(pac_host("proxy.lan"), "proxy.lan");
        assert_eq!(pac_host("[::1]"), "[::1]");
    }

    #[test]
    fn ipv6_host_is_bracketed_in_body() {
        let empty: Vec<Matcher> = vec![];
        let p = PacParams {
            proxy_host: "::1",
            ..params(PacMode::HttpSocks, &empty)
        };
        let pac = generate_pac(&p);
        assert!(pac.contains("PROXY [::1]:3128"), "body={pac}");
        assert!(pac.contains("SOCKS5 [::1]:1080"), "body={pac}");
    }
}
